services:
  db:
    image: postgres:15-alpine
    container_name: postgres_django
    environment:
      POSTGRES_DB : ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_django
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend_react
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - backend
      
volumes:
  postgres_data: